name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout from git
      uses: actions/checkout@v3
    - name: Build
      run: echo "Build step"
    - name: Upload
      run: echo "Upload step
    - name: Finish
      run: echo "Finish step"
