name: Android CI(reusable work flow)

on:
  workflow_call:
    inputs:
      username:
        description: 'A username passed from the caller workflow'
        default: 'john-doe'
        required: false
        type: string

jobs:
  print-username:
    runs-on: ubuntu-latest

    steps:
      - name: Print the input name to STDOUT
        run: echo Hello, ${{ inputs.username }}.
      - name: Set the value to env
        run: echo "user_name_updated=Updated" >> $GITHUB_ENV

