name: Upload to App Gallery

on:
  push:
    branches: [ "master" ]

jobs:

  call-workflow-passing-data:
    uses: vlad-bursov/GithubActionsTest/.github/workflows/reusable_workflow.yml@master
    with:
      username: Vlodos

  upload:
    needs: call-workflow-passing-data
    runs-on: ubuntu-latest

    steps:
      - name: Upload
        run: echo "Upload to Play Market"
      - name: Finish
        run: echo "Finish uploading"
      - name: Print outputs
        run: echo ${{ needs.call-workflow-passing-data.outputs.first }}, ${{ needs.call-workflow-passing-data.outputs.second }}

