name: Upload to Play Market

on:
  push:
    branches: [ "master" ]

jobs:
  call-workflow-passing-data:
    uses: vlad-bursov/GithubActionsTest/.github/workflows/reusable_workflow.yml@master
    with:
      username: Vlodos

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Upload
        run: echo "Upload to Play Market"
      - name: Finish
        run: echo "Finish uploading"

